# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_inputWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InputWindow(object):
    def setupUi(self, InputWindow):
        InputWindow.setObjectName("InputWindow")
        InputWindow.resize(798, 600)
        InputWindow.setAutoFillBackground(False)
        InputWindow.setStyleSheet("background-color: rgb(115, 106, 255);\n"
"selection-color: rgb(252, 233, 79);\n"
"selection-background-color: rgb(196, 160, 0);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(InputWindow)
        self.centralwidget.setStyleSheet("color: rgb(255, 255, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.Title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.Title.setFont(font)
        self.Title.setStyleSheet("color: rgb(255, 255, 255);")
        self.Title.setTextFormat(QtCore.Qt.PlainText)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.verticalLayout.addWidget(self.Title)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ID = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ID.setFont(font)
        self.ID.setStyleSheet("color: rgb(255, 255, 255);")
        self.ID.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ID.setObjectName("ID")
        self.horizontalLayout.addWidget(self.ID)
        self.inputID = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.inputID.setFont(font)
        self.inputID.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.inputID.setObjectName("inputID")
        self.horizontalLayout.addWidget(self.inputID)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.NextButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NextButton.sizePolicy().hasHeightForWidth())
        self.NextButton.setSizePolicy(sizePolicy)
        self.NextButton.setMinimumSize(QtCore.QSize(31, 0))
        self.NextButton.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.NextButton.setFont(font)
        self.NextButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(193, 125, 17);\n"
"selection-background-color: rgb(233, 185, 110);")
        self.NextButton.setIconSize(QtCore.QSize(30, 30))
        self.NextButton.setObjectName("NextButton")
        self.horizontalLayout_2.addWidget(self.NextButton)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        InputWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(InputWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.menubar.setFont(font)
        self.menubar.setAutoFillBackground(False)
        self.menubar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        InputWindow.setMenuBar(self.menubar)
        self.new_act = QtWidgets.QAction(InputWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Downloads/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("../../../../Downloads/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.new_act.setIcon(icon)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.new_act.setFont(font)
        self.new_act.setObjectName("new_act")
        self.open_act = QtWidgets.QAction(InputWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../Downloads/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_act.setIcon(icon1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.open_act.setFont(font)
        self.open_act.setIconVisibleInMenu(True)
        self.open_act.setObjectName("open_act")
        self.save_act = QtWidgets.QAction(InputWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../Downloads/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_act.setIcon(icon2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.save_act.setFont(font)
        self.save_act.setObjectName("save_act")
        self.exit_act = QtWidgets.QAction(InputWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../Downloads/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_act.setIcon(icon3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.exit_act.setFont(font)
        self.exit_act.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.exit_act.setVisible(True)
        self.exit_act.setObjectName("exit_act")
        self.commit_act = QtWidgets.QAction(InputWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../../Downloads/commit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commit_act.setIcon(icon4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.commit_act.setFont(font)
        self.commit_act.setObjectName("commit_act")
        self.menuFile.addAction(self.new_act)
        self.menuFile.addAction(self.open_act)
        self.menuFile.addAction(self.save_act)
        self.menuFile.addAction(self.commit_act)
        self.menuFile.addAction(self.exit_act)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(InputWindow)
        QtCore.QMetaObject.connectSlotsByName(InputWindow)

    def retranslateUi(self, InputWindow):
        _translate = QtCore.QCoreApplication.translate
        InputWindow.setWindowTitle(_translate("InputWindow", "MainWindow"))
        self.Title.setText(_translate("InputWindow", "INFORMATION REGISTER"))
        self.ID.setText(_translate("InputWindow", "Student ID"))
        self.NextButton.setText(_translate("InputWindow", "Next"))
        self.menuFile.setTitle(_translate("InputWindow", "File"))
        self.new_act.setText(_translate("InputWindow", "New"))
        self.new_act.setShortcut(_translate("InputWindow", "Ctrl+N"))
        self.open_act.setText(_translate("InputWindow", "Open"))
        self.open_act.setShortcut(_translate("InputWindow", "Ctrl+O"))
        self.save_act.setText(_translate("InputWindow", "Save"))
        self.save_act.setShortcut(_translate("InputWindow", "Ctrl+S"))
        self.exit_act.setText(_translate("InputWindow", "Exit"))
        self.exit_act.setShortcut(_translate("InputWindow", "Ctrl+Esc"))
        self.commit_act.setText(_translate("InputWindow", "Commit"))
        self.commit_act.setShortcut(_translate("InputWindow", "Ctrl+C"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InputWindow = QtWidgets.QMainWindow()
    ui = Ui_InputWindow()
    ui.setupUi(InputWindow)
    InputWindow.show()
    sys.exit(app.exec_())
